import { CustomTheme } from '../types/theme';

export const defaultThemes: CustomTheme[] = [
  {
    id: 'dark-default',
    name: 'Dark Default',
    description: 'Modern dark theme with pink/magenta accents',
    isDark: true,
    isCustom: false,
    colors: {
      primary: '#E91E63',
      secondary: '#8B5CF6',
      background: '#0F0F23',
      surface: '#1E1E2E',
      text: {
        primary: '#F8FAFC',
        secondary: '#CBD5E1',
        disabled: '#64748B',
      },
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      border: '#334155',
      divider: '#475569',
      shadow: 'rgba(0, 0, 0, 0.3)',
      status: {
        active: '#10B981',
        inactive: '#64748B',
        pending: '#F59E0B',
        completed: '#3B82F6',
      },
      blockStatus: {
        empty: '#6B7280',
        assigned: '#F59E0B',
        planted: '#10B981',
        harvesting: '#8B5CF6',
        alert: '#EF4444',
      },
      gradients: {
        primary: ['#3B82F6', '#1D4ED8'],
        secondary: ['#8B5CF6', '#7C3AED'],
        background: ['#0F172A', '#1E293B'],
        card: ['#1E293B', '#334155'],
      },
    },
    typography: {
      fontFamily: {
        primary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        secondary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        mono: '"Fira Code", "Monaco", "Consolas", monospace',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.25,
        normal: 1.5,
        relaxed: 1.75,
      },
      letterSpacing: {
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
      },
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
      '3xl': '4rem',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    },
    borderRadius: {
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      easing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
    },
    layout: {
      maxWidth: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      breakpoints: {
        xs: 0,
        sm: 640,
        md: 768,
        lg: 1024,
        xl: 1280,
      },
    },
    assets: {
      logo: {
        primary: '/agritec-logo.svg',
        secondary: '/agritec-logo.svg',
        icon: '/agritec-logo-icon.svg',
        favicon: '/favicon.ico',
      },
      images: {
        background: '/background-dark.jpg',
        placeholder: '/placeholder-dark.svg',
        avatar: '/avatar-default.svg',
      },
      icons: {
        style: 'outlined',
        weight: 400,
      },
    },
  },
  {
    id: 'light-default',
    name: 'Light Default',
    description: 'Clean light theme with modern design',
    isDark: false,
    isCustom: false,
    colors: {
      primary: '#3B82F6',
      secondary: '#8B5CF6',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      text: {
        primary: '#1E293B',
        secondary: '#64748B',
        disabled: '#94A3B8',
      },
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      border: '#E2E8F0',
      divider: '#CBD5E1',
      shadow: 'rgba(0, 0, 0, 0.1)',
      status: {
        active: '#10B981',
        inactive: '#94A3B8',
        pending: '#F59E0B',
        completed: '#3B82F6',
      },
      blockStatus: {
        empty: '#6B7280',
        assigned: '#F59E0B',
        planted: '#10B981',
        harvesting: '#8B5CF6',
        alert: '#EF4444',
      },
      gradients: {
        primary: ['#3B82F6', '#1D4ED8'],
        secondary: ['#8B5CF6', '#7C3AED'],
        background: ['#FFFFFF', '#F8FAFC'],
        card: ['#F8FAFC', '#F1F5F9'],
      },
    },
    typography: {
      fontFamily: {
        primary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        secondary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        mono: '"Fira Code", "Monaco", "Consolas", monospace',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.25,
        normal: 1.5,
        relaxed: 1.75,
      },
      letterSpacing: {
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
      },
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
      '3xl': '4rem',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    },
    borderRadius: {
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      easing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
    },
    layout: {
      maxWidth: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      breakpoints: {
        xs: 0,
        sm: 640,
        md: 768,
        lg: 1024,
        xl: 1280,
      },
    },
    assets: {
      logo: {
        primary: '/agritec-logo.svg',
        secondary: '/agritec-logo.svg',
        icon: '/agritec-logo-icon.svg',
        favicon: '/favicon.ico',
      },
      images: {
        background: '/background-light.jpg',
        placeholder: '/placeholder-light.svg',
        avatar: '/avatar-default.svg',
      },
      icons: {
        style: 'outlined',
        weight: 400,
      },
    },
  },
  {
    id: 'zen-garden',
    name: 'Zen Garden',
    description: 'Peaceful zen-inspired theme with natural colors',
    isDark: true,
    isCustom: false,
    colors: {
      primary: '#4ECDC4',
      secondary: '#7FB069',
      background: '#1B4D3E',
      surface: '#2D1B69',
      text: {
        primary: '#F8FAFC',
        secondary: '#CBD5E1',
        disabled: '#64748B',
      },
      success: '#7FB069',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#4ECDC4',
      border: '#4ECDC4',
      divider: '#7FB069',
      shadow: 'rgba(27, 77, 62, 0.3)',
      status: {
        active: '#7FB069',
        inactive: '#64748B',
        pending: '#F59E0B',
        completed: '#4ECDC4',
      },
      blockStatus: {
        empty: '#6B7280',
        assigned: '#F59E0B',
        planted: '#7FB069',
        harvesting: '#8B5CF6',
        alert: '#EF4444',
      },
      gradients: {
        primary: ['#4ECDC4', '#7FB069'],
        secondary: ['#7FB069', '#4ECDC4'],
        background: ['#1B4D3E', '#2D1B69'],
        card: ['rgba(255, 255, 255, 0.95)', 'rgba(255, 255, 255, 0.9)'],
      },
    },
    typography: {
      fontFamily: {
        primary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        secondary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        mono: '"Fira Code", "Monaco", "Consolas", monospace',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.25,
        normal: 1.5,
        relaxed: 1.75,
      },
      letterSpacing: {
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
      },
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
      '3xl': '4rem',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    },
    borderRadius: {
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      easing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
    },
    layout: {
      maxWidth: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      breakpoints: {
        xs: 0,
        sm: 640,
        md: 768,
        lg: 1024,
        xl: 1280,
      },
    },
    assets: {
      logo: {
        primary: '/logo-zen.svg',
        secondary: '/logo-zen-secondary.svg',
        icon: '/logo-zen-icon.svg',
        favicon: '/favicon-zen.ico',
      },
      images: {
        background: '/background-zen.jpg',
        placeholder: '/placeholder-zen.svg',
        avatar: '/avatar-zen.svg',
      },
      icons: {
        style: 'rounded',
        weight: 400,
      },
    },
  },
  {
    id: 'agriculture-green',
    name: 'Agriculture Green',
    description: 'Natural green theme for agricultural applications',
    isDark: false,
    isCustom: false,
    colors: {
      primary: '#22C55E',
      secondary: '#16A34A',
      background: '#F0FDF4',
      surface: '#FFFFFF',
      text: {
        primary: '#14532D',
        secondary: '#166534',
        disabled: '#9CA3AF',
      },
      success: '#22C55E',
      warning: '#F59E0B',
      error: '#EF4444',
      info: '#3B82F6',
      border: '#BBF7D0',
      divider: '#DCFCE7',
      shadow: 'rgba(34, 197, 94, 0.1)',
      status: {
        active: '#22C55E',
        inactive: '#9CA3AF',
        pending: '#F59E0B',
        completed: '#16A34A',
      },
      blockStatus: {
        empty: '#6B7280',
        assigned: '#F59E0B',
        planted: '#22C55E',
        harvesting: '#16A34A',
        alert: '#EF4444',
      },
      gradients: {
        primary: ['#22C55E', '#16A34A'],
        secondary: ['#16A34A', '#15803D'],
        background: ['#F0FDF4', '#FFFFFF'],
        card: ['#FFFFFF', '#F0FDF4'],
      },
    },
    typography: {
      fontFamily: {
        primary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        secondary: '"Inter", "Roboto", "Helvetica", "Arial", sans-serif',
        mono: '"Fira Code", "Monaco", "Consolas", monospace',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: {
        tight: 1.25,
        normal: 1.5,
        relaxed: 1.75,
      },
      letterSpacing: {
        tight: '-0.025em',
        normal: '0',
        wide: '0.025em',
      },
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
      '3xl': '4rem',
    },
    shadows: {
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
    },
    borderRadius: {
      sm: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    animation: {
      duration: {
        fast: '150ms',
        normal: '300ms',
        slow: '500ms',
      },
      easing: {
        ease: 'ease',
        easeIn: 'ease-in',
        easeOut: 'ease-out',
        easeInOut: 'ease-in-out',
      },
    },
    layout: {
      maxWidth: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      breakpoints: {
        xs: 0,
        sm: 640,
        md: 768,
        lg: 1024,
        xl: 1280,
      },
    },
    assets: {
      logo: {
        primary: '/logo-agriculture.svg',
        secondary: '/logo-agriculture-secondary.svg',
        icon: '/logo-agriculture-icon.svg',
        favicon: '/favicon-agriculture.ico',
      },
      images: {
        background: '/background-agriculture.jpg',
        placeholder: '/placeholder-agriculture.svg',
        avatar: '/avatar-agriculture.svg',
      },
      icons: {
        style: 'outlined',
        weight: 400,
      },
    },
  },
];
